package com.ptcdepth.android

import org.junit.Assert.assertEquals
import org.junit.Test

class MavlinkCrcTest {
    @Test
    fun odometryReferencePacketHasOfficialChecksum() {
        // MAVLink 2 ODOMETRY packet generated by pymavlink/common.xml for:
        // sysid=2, compid=197, seq=0, time_usec=123456789, LOCAL_FRD/BODY_FRD.
        val packetWithoutCrc = hex(
            "fde900000002c54b0100" +
                "15cd5b07000000000000803f0000004000004040" +
                "0000803f000000000000000000000000" +
                "cdcccc3dcdcc4c3e9a99993e" +
                "000000000000000000000000" +
                "0000c07f".repeat(42) +
                "140c000364"
        )

        var crc = 0xFFFF
        // CRC starts at payload length, excluding the 0xFD magic byte.
        packetWithoutCrc.drop(1).forEach { crc = accumulate(it.toInt() and 0xFF, crc) }
        crc = accumulate(91, crc) // ODOMETRY CRC_EXTRA

        assertEquals(0x1AEA, crc)
    }

    private fun accumulate(value: Int, current: Int): Int {
        var tmp = (value xor (current and 0xFF)) and 0xFF
        tmp = (tmp xor (tmp shl 4)) and 0xFF
        return ((current ushr 8) xor (tmp shl 8) xor (tmp shl 3) xor (tmp ushr 4)) and 0xFFFF
    }

    private fun hex(value: String): ByteArray =
        value.chunked(2).map { it.toInt(16).toByte() }.toByteArray()
}
