models:
  depth_anything_v2_rel:
    model_path: "/home/arrl_server2/workspace/pr_depth/weights/depth_anything_v2"
    encoder: "vitl"

  depth_anything_v2_met:
    model_path: "/home/arrl_server2/workspace/pr_depth/weights/depth_anything_v2"
    encoder: "vitl"
    dataset: "vkitti"

  uni_depth:
    model_path: "/home/arrl_server2/workspace/pr_depth/weights/uni_depth"

  moge_v2:
    model_path: "/home/arrl_server2/workspace/pr_depth/weights/moge_v2/model.pt"

datasets:
  kitti:
    rgb_path: "/home/nas/Dataset2/KITTI/KITTI_RGB_Image"
    depth_path: "/home/nas/Dataset2/KITTI/KITTI_PointCloud"

  ms2:
    dataset_path: "/home/nas/Dataset1/MS2"

  tartanair:
    dataset_path: "/home/nas/Dataset3/TartanAir"

  eth3d:
    dataset_path: "/home/nas/Dataset3/ETH3D"

  euroc:
    dataset_path: "/home/nas/Dataset3/EuRoC"

  void:
    dataset_path: "/home/nas/Dataset3/void_release"
